spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bcp?serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    
